# Generated by Django 3.1.2 on 2020-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_player', '0002_session_consumer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='media_url',
            field=models.URLField(null=True, verbose_name='Media URL'),
        ),
        migrations.AddField(
            model_name='session',
            name='metadata',
            field=models.TextField(default='', verbose_name='Metadata'),
        ),
    ]
